deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "Bootbusiness"
  env: "Bootbusiness-env"
  bucket_name: "elasticbeanstalk-eu-central-1-934272981507"
  bucket_path: "Bootbusiness"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY